# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "utils.ipynb",
         "hello_world": "template.ipynb"}

modules = ["core.py",
           "experimental.py",
           "template.py",
           "utils.py"]

doc_url = "https://leemengtaiwan.github.io/pytorch_lightning_applications/"

git_url = "https://github.com/leemengtaiwan/pytorch_lightning_applications/tree/master/"

def custom_doc_links(name): return None
