# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/experimental.ipynb (unless otherwise specified).

__all__ = ['logger']

# Cell
import json
import logging

logger = logging.getLogger()
logger.setLevel("INFO")