# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/template.ipynb (unless otherwise specified).

__all__ = ['logger', 'hello_world']

# Cell
import json
import logging

logger = logging.getLogger()
logger.setLevel("INFO")

# Cell
def hello_world():
    return "hello world!"