# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "utils.ipynb",
         "get_data_root": "data.ipynb",
         "ImageOnlyDataset": "data.ipynb",
         "get_dataset": "data.ipynb",
         "get_data_loader": "data.ipynb",
         "DIM_CHANNEL_MULTIPLIER": "gan.ipynb",
         "KERNEL_SIZE": "gan.ipynb",
         "LATENT_DIM": "gan.ipynb",
         "DIM": "gan.ipynb",
         "CHANNELS": "gan.ipynb",
         "NORM": "gan.ipynb",
         "BATCH_SIZE": "gan.ipynb",
         "get_n_samplings": "gan.ipynb",
         "get_norm2d": "gan.ipynb",
         "get_activation": "gan.ipynb",
         "UpsampleConv2d": "gan.ipynb",
         "UnsqueezeLatent": "gan.ipynb",
         "SqueezeLogit": "gan.ipynb",
         "DownsampleConv2d": "gan.ipynb",
         "ConvGenerator": "gan.ipynb",
         "get_generater": "gan.ipynb",
         "get_discriminator": "gan.ipynb",
         "GAN": "gan.ipynb",
         "get_gan_losses_fns": "gan.loss.ipynb",
         "get_adversarial_losses_fns": "gan.loss.ipynb",
         "Identity": "layers.ipynb",
         "download_gdrive": "utils.ipynb"}

modules = ["core.py",
           "data.py",
           "experimental.py",
           "gan.py",
           "gan/loss.py",
           "layers.py",
           "utils.py"]

doc_url = "https://leemengtaiwan.github.io/practical_ai/"

git_url = "https://github.com/leemengtaiwan/practical_ai/tree/master/"


def custom_doc_links(name): return None
