# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/vision.gan.gp.ipynb (unless otherwise specified).

__all__ = ['logger']


# Cell
import logging


logger = logging.getLogger()
logger.setLevel("INFO")