# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/vision.gan.hparam.ipynb (unless otherwise specified).

__all__ = ['logger', 'DATASET', 'LATENT_DIM', 'DIM', 'CHANNELS', 'GENERATOR_TYPE', 'DISCRIMINATOR_TYPE',
           'ADVERSARIAL_LOSS_TYPE', 'NORM_TYPE', 'DIM_CHANNEL_MULTIPLIER', 'KERNEL_SIZE', 'BATCH_SIZE', 'LR', 'BETA1',
           'BETA2']


# Cell
import logging


logger = logging.getLogger()
logger.setLevel("INFO")


# Cell
DATASET = "mnist"
LATENT_DIM = 128
DIM = 32
CHANNELS = 1


# Cell
GENERATOR_TYPE = "conv"
DISCRIMINATOR_TYPE = "conv"
ADVERSARIAL_LOSS_TYPE = "gan"
NORM_TYPE = "batch"
DIM_CHANNEL_MULTIPLIER = 8
KERNEL_SIZE = 4


# Cell
BATCH_SIZE = 32
LR = 2e-4
BETA1 = 0.5
BETA2 = 0.999