# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "vision.gan.loss.ipynb",
         "get_data_root": "data.ipynb",
         "ImageOnlyDataset": "data.ipynb",
         "ImageDataset": "data.ipynb",
         "StickerDataset": "data.ipynb",
         "get_dataset": "data.ipynb",
         "get_dataloader": "data.ipynb",
         "Identity": "layers.ipynb",
         "ensure_reproducible": "utils.ipynb",
         "download_gdrive": "utils.ipynb",
         "SPECTRAL_NORM": "vision.gan.core.ipynb",
         "get_n_samplings": "vision.gan.core.ipynb",
         "get_norm2d": "vision.gan.core.ipynb",
         "get_activation": "vision.gan.core.ipynb",
         "init_xavier_uniform": "vision.gan.core.ipynb",
         "UpsampleConv2d": "vision.gan.core.ipynb",
         "UnsqueezeLatent": "vision.gan.core.ipynb",
         "SqueezeLogit": "vision.gan.core.ipynb",
         "DownsampleConv2d": "vision.gan.core.ipynb",
         "ConvGenerator": "vision.gan.core.ipynb",
         "ConvDiscriminator": "vision.gan.core.ipynb",
         "get_generater": "vision.gan.core.ipynb",
         "get_discriminator": "vision.gan.core.ipynb",
         "GAN": "vision.gan.core.ipynb",
         "DATASET": "vision.gan.hparam.ipynb",
         "LATENT_DIM": "vision.gan.hparam.ipynb",
         "DIM": "vision.gan.hparam.ipynb",
         "CHANNELS": "vision.gan.hparam.ipynb",
         "GENERATOR_TYPE": "vision.gan.hparam.ipynb",
         "DISCRIMINATOR_TYPE": "vision.gan.hparam.ipynb",
         "ADVERSARIAL_LOSS_TYPE": "vision.gan.hparam.ipynb",
         "NORM_TYPE": "vision.gan.hparam.ipynb",
         "DIM_CHANNEL_MULTIPLIER": "vision.gan.hparam.ipynb",
         "KERNEL_SIZE": "vision.gan.hparam.ipynb",
         "BATCH_SIZE": "vision.gan.hparam.ipynb",
         "LR": "vision.gan.hparam.ipynb",
         "BETA1": "vision.gan.hparam.ipynb",
         "BETA2": "vision.gan.hparam.ipynb",
         "create_like": "vision.gan.loss.ipynb",
         "ones_like": "vision.gan.loss.ipynb",
         "zeros_like": "vision.gan.loss.ipynb",
         "get_adversarial_loss_fns": "vision.gan.loss.ipynb",
         "draw_adversarial_loss_fns": "vision.gan.loss.ipynb",
         "get_gan_loss_fns": "vision.gan.loss.ipynb",
         "get_lsgan_loss_fns": "vision.gan.loss.ipynb",
         "get_wgan_loss_fns": "vision.gan.loss.ipynb",
         "get_hinge_loss_fns": "vision.gan.loss.ipynb",
         "get_sngan_loss_fns": "vision.gan.loss.ipynb"}

modules = ["core.py",
           "data.py",
           "experimental.py",
           "layers.py",
           "utils.py",
           "vision/gan/core.py",
           "vision/gan/gp.py",
           "vision/gan/hparams.py",
           "vision/gan/loss.py"]

doc_url = "https://leemengtaiwan.github.io/learnable_ai/"

git_url = "https://github.com/leemengtaiwan/learnable_ai/tree/master/"


def custom_doc_links(name): return None
