# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/layers.ipynb (unless otherwise specified).

__all__ = ['logger', 'Identity']


# Cell
import torch
from torch import nn
import logging

logger = logging.getLogger()
logger.setLevel("INFO")


# Cell
class Identity(nn.Module):

    def __init__(self, *args, **kwargs):
        super().__init__()

    def forward(self, x):
        return x